import type { TTestimonial } from "../types";

export type TCredential = TTestimonial & {
  issued?: string;
  credentialId?: string;
  credentialUrl?: string;
  featured?: boolean;
};

/** Featured first — shown by default. Remaining available via View more. */
export const credentials: TCredential[] = [
  {
    name: "Recognition Award",
    designation: "Achievement",
    company: "OmniContact",
    testimonial:
      "Certificate of Recognition for exceptional hard work and dedication during 2024.",
    image: "",
    issued: "2024",
    featured: true,
  },
  {
    name: "Google Cybersecurity",
    designation: "Professional Certificate",
    company: "Google",
    testimonial: "Google Cybersecurity Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "V453I3CEC3XV",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/V453I3CEC3XV",
    featured: true,
  },
  {
    name: "Google AI",
    designation: "Professional Certificate",
    company: "Google",
    testimonial: "Google AI Professional Certificate.",
    image: "",
    issued: "Apr 2026",
    credentialId: "KX8V3T87UFDX",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/KX8V3T87UFDX",
    featured: true,
  },
  {
    name: "IBM IT Support",
    designation: "Professional Certificate",
    company: "IBM",
    testimonial: "IBM IT Support Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "MXP2090WAZJF",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/MXP2090WAZJF",
    featured: true,
  },
  {
    name: "OCI Generative AI Professional",
    designation: "Certification",
    company: "Oracle",
    testimonial:
      "Oracle Cloud Infrastructure 2025 Certified Generative AI Professional.",
    image: "",
    issued: "Aug 2025",
    credentialId: "OC6837973",
    // Public cert page (Oracle has no anonymous ID lookup). Swap for CertView sharebadge when available.
    credentialUrl:
      "https://education.oracle.com/oracle-cloud-infrastructure-2025-certified-generative-ai-professional/trackp_OCI2025GAIOCP",
    featured: true,
  },
  {
    name: "Social Computing",
    designation: "Course Certificate",
    company: "The Johns Hopkins University",
    testimonial: "Social Computing — The Johns Hopkins University.",
    image: "",
    issued: "Jun 2026",
    credentialId: "3RKU91XCLSRM",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/3RKU91XCLSRM",
    featured: true,
  },
  {
    name: "Cyber Security: Essentials for GRC",
    designation: "Course Certificate",
    company: "Macquarie University",
    testimonial:
      "Cyber Security: Essentials for Governance, Risk & Compliance.",
    image: "",
    issued: "May 2026",
    credentialId: "7UATRENGSQ8X",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/7UATRENGSQ8X",
    featured: true,
  },
  {
    name: "Mastering ISO 27001 Controls",
    designation: "Course Certificate",
    company: "Packt",
    testimonial: "Mastering ISO 27001 Controls: Implementation and Auditing.",
    image: "",
    issued: "May 2026",
    credentialId: "FEAKJNQQXFIU",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/FEAKJNQQXFIU",
    featured: true,
  },
  {
    name: "Hands-on Data Centric Visual AI",
    designation: "Course Certificate",
    company: "University of California, Davis",
    testimonial: "Hands-on Data Centric Visual AI Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "YUWRXOZ1M8XU",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/YUWRXOZ1M8XU",
    featured: true,
  },
  {
    name: "OCI AI Foundations",
    designation: "Certification",
    company: "Oracle",
    testimonial:
      "Oracle Cloud Infrastructure Certified AI Foundations Associate (2025).",
    image: "",
    issued: "2025",
    featured: false,
  },
  {
    name: "OCI Foundations",
    designation: "Certification",
    company: "Oracle",
    testimonial:
      "Oracle Cloud Infrastructure Certified Foundations Associate (2025).",
    image: "",
    issued: "2025",
    featured: false,
  },
  {
    name: "Oracle Data Platform",
    designation: "Certification",
    company: "Oracle",
    testimonial: "Oracle Data Platform Certified Foundations Associate (2025).",
    image: "",
    issued: "2025",
    featured: false,
  },
  {
    name: "Fusion AI Agent Studio",
    designation: "Certification",
    company: "Oracle",
    testimonial:
      "Oracle Fusion AI Agent Studio Foundations Associate (2025).",
    image: "",
    issued: "2025",
    featured: false,
  },
  {
    name: "Cisco Network Basics",
    designation: "Certification",
    company: "Cisco Networking Academy",
    testimonial: "Cisco Networking Academy — Network Basics.",
    image: "",
    issued: "2025",
    featured: false,
  },
  {
    name: "Cyber Security: GRC Part 1 — Governance",
    designation: "Course Certificate",
    company: "Macquarie University",
    testimonial: "Cyber Security: GRC Part 1 - Governance.",
    image: "",
    issued: "May 2026",
    credentialId: "DC1XKT1LRFA6",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/DC1XKT1LRFA6",
  },
  {
    name: "Foundations of Cybersecurity",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Foundations of Cybersecurity Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "LQUHLGI5HJPF",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/LQUHLGI5HJPF",
  },
  {
    name: "Play It Safe: Manage Security Risks",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Play It Safe: Manage Security Risks.",
    image: "",
    issued: "May 2026",
    credentialId: "4WE6FWKMMP3K",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/4WE6FWKMMP3K",
  },
  {
    name: "Connect and Protect: Networks and Network Security",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Connect and Protect: Networks and Network Security.",
    image: "",
    issued: "May 2026",
    credentialId: "01PWNFZ4OSHH",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/01PWNFZ4OSHH",
  },
  {
    name: "Assets, Threats, and Vulnerabilities",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Assets, Threats, and Vulnerabilities.",
    image: "",
    issued: "May 2026",
    credentialId: "DMDVWDOG81L7",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/DMDVWDOG81L7",
  },
  {
    name: "Sound the Alarm: Detection and Response",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Sound the Alarm: Detection and Response.",
    image: "",
    issued: "May 2026",
    credentialId: "R4MXVPLY7F9H",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/R4MXVPLY7F9H",
  },
  {
    name: "Automate Cybersecurity Tasks with Python",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Automate Cybersecurity Tasks with Python.",
    image: "",
    issued: "May 2026",
    credentialId: "HJS7YLEM5NFB",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/HJS7YLEM5NFB",
  },
  {
    name: "Tools of the Trade: Linux and SQL",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Tools of the Trade: Linux and SQL.",
    image: "",
    issued: "May 2026",
    credentialId: "3AX26AJMXBA1",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/3AX26AJMXBA1",
  },
  {
    name: "Introduction to Cybersecurity Essentials",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Introduction to Cybersecurity Essentials.",
    image: "",
    issued: "May 2026",
    credentialId: "KKGZCAVF526T",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/KKGZCAVF526T",
  },
  {
    name: "Introduction to Technical Support",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Introduction to Technical Support.",
    image: "",
    issued: "May 2026",
    credentialId: "2EGQSWJE7XU9",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/2EGQSWJE7XU9",
  },
  {
    name: "Introduction to Hardware and Operating Systems",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Introduction to Hardware and Operating Systems.",
    image: "",
    issued: "May 2026",
    credentialId: "AW9X7AIBH6Q8",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/AW9X7AIBH6Q8",
  },
  {
    name: "Introduction to Networking and Storage",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Introduction to Networking and Storage.",
    image: "",
    issued: "May 2026",
    credentialId: "E9QRGR4D913A",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/E9QRGR4D913A",
  },
  {
    name: "Introduction to Software, Programming, and Databases",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Introduction to Software, Programming, and Databases.",
    image: "",
    issued: "May 2026",
    credentialId: "H49I462KB2XM",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/H49I462KB2XM",
  },
  {
    name: "Practice Exam for CompTIA Tech+",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Practice Exam for CompTIA Tech+ Certification.",
    image: "",
    issued: "May 2026",
    credentialId: "EH4Q1MYM394T",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/EH4Q1MYM394T",
  },
  {
    name: "Tech Support Career Guide and Interview Preparation",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Tech Support Career Guide and Interview Preparation.",
    image: "",
    issued: "May 2026",
    credentialId: "WHFMDXABISO8",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/WHFMDXABISO8",
  },
  {
    name: "Introduction to Cloud Computing",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Introduction to Cloud Computing.",
    image: "",
    issued: "Apr 2026",
    credentialId: "8LSJ2AEGMQLM",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/8LSJ2AEGMQLM",
  },
  {
    name: "Introduction to DevOps",
    designation: "Course Certificate",
    company: "IBM",
    testimonial: "Introduction to DevOps.",
    image: "",
    issued: "Apr 2026",
    credentialId: "8R33ZFFVZR2I",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/8R33ZFFVZR2I",
  },
  {
    name: "IBM Z Day 2025 — AI & Data",
    designation: "Event Certificate",
    company: "IBM",
    testimonial: "IBM Z Day 2025 - AI & Data.",
    image: "",
    issued: "Dec 2025",
  },
  {
    name: "IBM Z Day 2025 — Security",
    designation: "Event Certificate",
    company: "IBM",
    testimonial: "IBM Z Day 2025 - Security.",
    image: "",
    issued: "Dec 2025",
  },
  {
    name: "AI for Data Analysis",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "AI for Data Analysis.",
    image: "",
    issued: "Apr 2026",
    credentialId: "G8F5E3LW1Q0I",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/G8F5E3LW1Q0I",
  },
  {
    name: "AI for Content Creation",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "AI for Content Creation.",
    image: "",
    issued: "Apr 2026",
    credentialId: "V6LI2JDLGOLZ",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/V6LI2JDLGOLZ",
  },
  {
    name: "AI for Writing and Communicating",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "AI for Writing and Communicating.",
    image: "",
    issued: "Apr 2026",
    credentialId: "Z5J4GJXRNS6D",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/Z5J4GJXRNS6D",
  },
  {
    name: "AI for Research and Insights",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "AI for Research and Insights.",
    image: "",
    issued: "Apr 2026",
    credentialId: "71KZX6LOSP6E",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/71KZX6LOSP6E",
  },
  {
    name: "Start the UX Design Process",
    designation: "Course Certificate",
    company: "Google",
    testimonial: "Start the UX Design Process: Empathize, Define, and Ideate.",
    image: "",
    issued: "Apr 2026",
    credentialId: "SC75T7L5XSIY",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/SC75T7L5XSIY",
  },
  {
    name: "Training AI with Humans",
    designation: "Course Certificate",
    company: "The Johns Hopkins University",
    testimonial: "Training AI with Humans Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "E6IF2AHP7VER",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/E6IF2AHP7VER",
  },
  {
    name: "Data for Machine Learning",
    designation: "Course Certificate",
    company: "Amii",
    testimonial: "Data for Machine Learning Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "X1EM66YHQPMN",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/X1EM66YHQPMN",
  },
  {
    name: "H2O Label Genie Starter Track",
    designation: "Course Certificate",
    company: "H2O.ai",
    testimonial: "H2O Label Genie Starter Track Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "OHFDHX42PWEW",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/OHFDHX42PWEW",
  },
  {
    name: "Annotate and Analyze Objects for Vision",
    designation: "Course Certificate",
    company: "Coursera",
    testimonial: "Annotate and Analyze Objects for Vision Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "EIFE65NXIVI4",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/EIFE65NXIVI4",
  },
  {
    name: "Forage Academy — Data Labeling Job Simulation",
    designation: "Job Simulation",
    company: "Forage",
    testimonial: "Data Labeling Job Simulation Certificate.",
    image: "",
    issued: "May 2026",
    credentialId: "nAsWTgN8TrXwYAgfT",
    // Replace with the share URL from your Forage certificate PDF when you have it.
    credentialUrl: "https://www.theforage.com/",
  },
];
